/**
 * 
 */
package com.teksystems.salestaxexercise.runners;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.teksystems.salestaxexercise.Receiptable;

/**
 * Contains the static main function used to run and test the entire project.
 * 
 * Builds and runs the 3 test cases in the problem, then prints the requested
 * output to the console.
 * 
 * Also saves the Receipt object(s) generated by running the main function in
 * a member collection so they can be inspected by an automated end-to-end test
 * 
 * @author Andrew
 *
 */
public class SalesTaxExerciseRunner {
	
	private static ArrayList<Receiptable> outputReceipts = new ArrayList<Receiptable>(); 

	/**
	 * @return the outputReceipts
	 */
	public static List<Receiptable> getOutputReceipts() {
		return outputReceipts;
	}

	/**
	 * @param args ignored
	 */
	public static void main(String[] args) {
		outputReceipts.addAll(Arrays.asList(
				TestHelpers.TEST_BASKET_1,
				TestHelpers.TEST_BASKET_2,
				TestHelpers.TEST_BASKET_3
		));
		int count = 1;
		for (Receiptable receipt : outputReceipts) {
			System.out.println("Output " + count + ":");
			receipt.printReceipt();
			System.out.println();
			count++;
		}
	}

}
